Algoritmo "Aula04 - correção nota e media final  "

Var
// Seção de Declarações das variáveis 
n1 , n2 , n3 , mediaFinal  : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    //    entrada
// 3 notas
    leia(n1)
    leia(n2)
    leia(n3)
    
    //   processo
//calcular media (anexo)
mediaFinal <- (n1 * 2 + n2 * 3 + n3 * 5)/10
    
    
    
    
    // saida
//media do aluno
escreval ("Media Final : ", mediaFinal)



Fimalgoritmo