Algoritmo "Aula 04 - Correção Time e gols arquitetura do enquanto  "

Var
// Seção de Declarações das variáveis 

contador : inteiro
   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// processo
   // repetição de 10
   // (contador > 0) e (contador < 10)
   
 contador <- 1
 enquanto (contador <= 10) faça
  escreval(" 8 x ",contador,"=", contador * 8)
  contador <- contador + 1
                    // tem que atribuir um valor ao contador



fimEnquanto

Fimalgoritmo