Algoritmo "aula 3 - condicional"

Var
// Seção de Declarações das variáveis 
numero : inteiro
codicao : logico

Inicio
condicao <- falso
nome <- 1
// se numero for 1 é numero um
//senao for 1, não é numero um
se (nome = "1" ) entao
   escreval("estou o se")
   escreval ("Sejabem vindo Vicor !")
    escreval(" numero 1")
   senao
senao
     escreval ("estou no senao")
     escreval ("Usuario não cadastrado  ")
     escreval ("Outro numero ")
 fimSe

Fimalgoritmo