Algoritmo "Correção aula 1 antecessor e sucessor  "
Var
numero, antecessor : INTEIRO


inicio

// 1)Escreva um algoritimo para ler um valor e
//escreverum valor e escrever seu antecessor
// ENTRADA
//RECEBER UM NUMERO
ESCREVAL("Digite um numero para verificar o antecessor:")
leia(numero)

//PROCESSO
// numero -1
antecessor <- numero -1





// saida
// escrever o antecessor
LimpaTela
escreval ("O antecessor do numero ", numero, " é ", antecessor)




Fimalgoritmo