Algoritmo "Aula 3.4 exercicio "
// Desenvolva um sistema onde exista uma maneira de salvar as notas
// de Jõao, Maria ou Pedro. O usuário deverá selecionar qual
// aluno deverá ter a nota salva!
// e assim que salva, mostre uma mensagem ao usuario

Var
 numero : inteiro
// Seção de Declarações das variáveis 

 

Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreval ("insira a nota de maria ")
 
 
Fimalgoritmo