Algoritmo " exeplos Aula 3.2"



Var
// INFOS QUE JA ESTÃO SALVAS
usuarioSalvo , senha : CARACTERE
// INFOS QUE ELE VAI DIGITAR

USUARIO, SENHA : CARACTERE

Inicio
usuarioSalvo <- " FULANO"
senhaSalva <- "senha123"

leia (usuario )
leia (senha)

senao
se (    usuarioSalavo = usuario ) e (senhaSalva = senha ) entao

escreval("Login efetuado com sucesso!")
senao
escreval ("Usuario ou senha incorreta ")
fimSe

Fimalgoritmo